services:
  - type: web
    name: rick-morty-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/main
    envVars:
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        sync: false # Configurar en el Dashboard (ej. https://rick-morty-frontend.onrender.com)
